# Use uma imagem base do Python
FROM python:3.8-slim-buster

# Defina o diretório de trabalho
WORKDIR /app

# Copie os requisitos do projeto e instale as dependências
COPY requirements.txt requirements.txt
RUN pip install --upgrade pip && pip install -r requirements.txt

# Adicione download Werkzeug
RUN pip install Werkzeug==2.0.1

# Copie o restante do código da aplicação
COPY . .

# porta que a aplicação usará
EXPOSE 5000

# Defina o comando para iniciar a aplicação
CMD ["python", "app.py"]
