# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: nodeless
service: vision

provider:
  name: aws
  runtime: python3.9

functions:
  health:
    handler: handler.health
    events:
      - httpApi:
          path: /
          method: get
  v1Description:
    handler: handler.v1_description
    events:
      - httpApi:
          path: /v1
          method: get
  v2Description:
    handler: handler.v2_description
    events:
      - httpApi:
          path: /v2
          method: get
  v1Vision: 
    handler: handler.v1_vision
    events:
      - httpApi:
          path: /v1/vision
          method: post
  v2Vision: 
    handler: handler.v2_vision
    events:
      - httpApi:
          path: /v2/vision
          method: post
